name: tex-match
icon: snap/gui/tex-match.svg
adopt-info: tex-match

base: core20
confinement: strict

build-packages:
  - gcc
  - libc6-dev
  - libdbus-1-dev

parts:
  tex-match:
    plugin: rust
    source: .
    parse-info:
      - TeX-Match-Linux/data/fyi.zoey.TeX-Match.metainfo.xml
    rust-path:
      - TeX-Match-Linux

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: fyi.zoey.TeX-Match

apps:
  tex-match:
    command: bin/tex-match
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
    slots:
      - dbus-daemon
    common-id: fyi.zoey.TeX-Match
